#!/bin/bash
# On definit l'adresse de la prise en variable au cas ou on veut changer l'adresse
addr="192.168.33.1"
# Recupere la consommation electrique
conso=$(curl -X GET $addr/meter/0 --silent | jq .power)
# Affiche la conso
echo -e "Consommation actuelle de la prise : $conso\n"
