#!/bin/bash
curl http://192.168.33.1/relay/0?turn=off --silent
# Affiche l'etat de la prise pour s'assurer qu'elle est allumee
etat=$(curl http://192.168.33.1/relay/0?turn=off --silent | jq .ison)
# Affiche l'etat de la prise apres l'avoir eteinte, si l'etat n'est pas a false previent que le script ne s'est pas bien execute
if [ "$etat" == "false" ]
then
	echo -e "\nLa prise est eteinte\n"
else
	echo -e "\nLa prise ne s'est pas bien eteinte"
fi
