#!/bin/bash
curl http://192.168.33.1/relay/0?turn=on --silent
# Affiche l'etat de la prise pour s'assurer qu'elle est allumee
etat=$(curl http://192.168.33.1/relay/0?turn=on --silent | jq .ison)
# Affiche l'etat de la prise apres l'allumage, si l'etat n'est pas a true previent que le script ne s'est pas bien execute
if [ "$etat" == "true" ]
then
	echo -e "\nLa prise est allumee\n"
else
	echo -e "\nLa prise ne s'est pas bien allumee"
fi
