#!/bin/bash
# On definit l'adresse de la prise en variable au cas ou on veut changer l'adresse
addr1=10.202.255.252
addr2=10.202.255.253
# Recupere la consommation electrique
conso1=$(curl -X GET $addr1/meter/0 --silent | jq .power)
conso2=$(curl -X GET $addr2/meter/0 --silent | jq .power)
# Affiche la conso
echo -e "Consommation actuelle de la prise 1 : $conso1\n"
echo -e "Consommation actuelle de la prise 2 : $conso2\n"
